### ISSUE TITLE
Exception in adding InkCanvas wpf 

### ISSUE THREAD

**Issue by himanshueip** [MicrosoftDocs/windows-uwp#2724]
[issue_signature_ink_canvass.txt](https://github.com/MicrosoftDocs/windows-uwp/files/5287912/issue_signature_ink_canvass.txt)

[Enter feedback here]
Following page https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-2
I have performed the steps and i faced the following execption while debugging it
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='The invocation of the constructor on type 'Microsoft.Toolkit.Wpf.UI.Controls.InkCanvas' that matches the specified binding constraints threw an exception.' Line number '75' and line position '14'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ContosoExpenses.Views.ExpenseDetail.InitializeComponent() in C:\Users\max\Source\Repos\AppConsult-WinAppsModernizationWorkshop\Exercise2\01-Start\ContosoExpenses\Views\ExpenseDetail.xaml:line 1
   at ContosoExpenses.Views.ExpenseDetail..ctor() in C:\Users\max\Source\Repos\AppConsult-WinAppsModernizationWorkshop\Exercise2\01-Start\ContosoExpenses\Views\ExpenseDetail.xaml.cs:line 27
   at ContosoExpenses.Views.ExpensesList.<>c.<.ctor>b__0_1(SelectedExpenseMessage message) in C:\Users\max\Source\Repos\AppConsult-WinAppsModernizationWorkshop\Exercise2\01-Start\ContosoExpenses\Views\ExpensesList.xaml.cs:line 37

Inner Exception 1:
TypeInitializationException: The type initializer for 'Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHostBase' threw an exception.

Inner Exception 2:
TypeLoadException: Could not find Windows Runtime type 'Windows.UI.Xaml.Hosting.XamlSourceFocusNavigationReason'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badad06e-48a0-0a8d-e5e1-d0c8573dbc3e
* Version Independent ID: 313ee3ec-bcc2-cb3a-ac3f-5434f395ab6f
* Content: [Add a UWP InkCanvas control using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-2)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you encountered this issue. I went through the walkthrough steps again and did not encounter this problem. Please confirm that you are following the setup steps and instructions, and if you still encounter the same issue, please report it in the [Microsoft.Toolkit.Win32](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues) repo (this is the open source repo where XAML Islands code is being published, and the developers respond to feedback/bugs against the controls there).
