### ISSUE TITLE
InitializeDatabase() gives SQLite syntax error

### ISSUE THREAD

**Issue by binaryfunt** [MicrosoftDocs/windows-uwp#380]
From the `InitializeDatabase()` method

    String tableCommand = "CREATE TABLE IF NOT " +
            "EXISTS MyTable (Primary_Key INTEGER PRIMARY KEY AUTOINCREMENT, " +
            "Text_Entry NVARCHAR(2048) NULL)";

Is there something wrong with that bit (I don't have much experience with SQL)? It gives me the following SqliteException.

>Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'near "NULL": syntax error'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at DataAccessLibrary.DataAccess.InitializeDatabase()

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by binaryfunt** [comment]
I figured out why I was getting the error. It was because I had omitted the final `)` after `NULL` earlier, but when I corrected that, the DataAccessLibrary project was not getting rebuilt, so the error was persisting.

I fixed this by right clicking on my UWP project in the Solution Explorer, then clicking `Build Dependencies > Project Build Order...`, and in the dialog, ticking `DataAccessLibrary`.

Perhaps it would be a good idea to add a line in the doc about adding that build dependency, otherwise it could leave people scratching their heads when changing the DataAccess class has no effect. I'm opening a new issue about that.
