### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sweiner123** [MicrosoftDocs/windows-uwp#3931]
Version: 0.60.0.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True
Date: 7/8/2022 2:28:08 PM
Exception:
System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.System.Collections.ICollection.CopyTo(Array array, Int32 arrayIndex)
   at System.Collections.ArrayList.InsertRange(Int32 index, ICollection c)
   at System.Windows.Data.ListCollectionView.<RefreshOverride>b__1_0()
   at MS.Internal.Data.SynchronizationInfo.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.BindingOperations.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.PostChange(NotifyCollectionChangedEventArgs args)
   at PowerLauncher.ViewModel.MainViewModel.<>c__DisplayClass123_0.<UpdateResultsListViewAfterQuery>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@sweiner123 - Please re-submit this issue in the PowerToys product repo at https://github.com/microsoft/PowerToys/issues.

This repo is only for issues pertaining to the PowerToys documentation. 

Thanks!
