### ISSUE TITLE
Designer Error System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by KlingeSean** [MicrosoftDocs/windows-uwp#4016]
Getting an error in my UWP Designer..

I don't know how to fix it..

This happens when i make a new project aswell.

System.IO.FileNotFoundException
Could not find file 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0\Windows.winmd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.ShadowCopy.HostShadowCacheContent.EnsureItemCached(String source, String destination)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.ShadowCopy.HostShadowCacheContent.SyncItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.ShadowCopy.HostShadowCacheContent.SyncFolder(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.DesignTools.UwpDesignerHost.ShadowCopy.AppxPlatformOnlyShadowCopyWorker.<>c__DisplayClass6_0.<CopyProjectContentAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostPlatformBase.<EnsureProjectPayloadAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.UwpDesignerHost.UwpHostPlatform.<EnsureProjectPayloadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostPlatformBase.<EnsureShadowCacheContent>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostPlatformBase.<CreateSurfaceProcessAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.SurfaceIsolation.SurfaceProcessContext.<EnsureSurfaceProcessAsyncCore>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.SurfaceIsolation.SurfaceProcessContext.<EnsureSurfaceProcessAsyncInternal>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.IsolatedSurfaceImageHost.<CreateSurfaceAsync>d__67.MoveNext()

System.AggregateException
One or more errors occurred.

**Comment by GrantMeStrength** [comment]
I'm sorry but this isn't a documentation issue. You might want to ask on the Microsoft Q&A Forum.
-John
