### ISSUE TITLE
CoreMLTools Installation under Python3 in Windows Anaconda

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/windows-uwp#445]
Note that CoreMLTools doesn't support "pip install coremltools" under Python3 with Windows. Users need to use $ pip install git+https://github.com/apple/coremltools to install CoreMLTools from the source from GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c28f709-f39f-51e1-dbd6-049496ec9b8d
* Version Independent ID: b2a668cf-c3b8-2236-2f6c-0e876f4393a0
* Content: [Convert existing ML models to ONNX - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/conversion-samples)
* Content Source: [windows-apps-src/machine-learning/conversion-samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/conversion-samples.md)
* Service: **unspecified**
* GitHub Login: @wschin
* Microsoft Alias: **wechi**

**Comment by rey-okujet** [comment]
I tried to install kraken on a python environment and got this error below:
ERROR: Could not find a version that satisfies the requirement coremltools (from kraken) (from versions: none)
ERROR: No matching distribution found for coremltools (from kraken)

As I use windows, I used the command suggested in the above post and could not complete the download of CoreMLTools with a longer error message. Has anyone had this issue before?

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\reyno\Envs\p3env-wk2\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\reyno\\AppData\\Local\\Temp\\pip-req-build-c80vbasj\\setup.py'"'"'; __file__='"'"'C:\\Users\\reyno\\AppData\\Local\\Temp\\pip-req-build-c80vbasj\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\pip-egg-info'
         cwd: C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\setup.py", line 11, in <module>
        from coremltools import __version__
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\__init__.py", line 50, in <module>
        from . import converters
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\converters\__init__.py", line 9, in <module>
        from . import xgboost
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\converters\xgboost\__init__.py", line 6, in <module>
        from ._tree import convert
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\converters\xgboost\_tree.py", line 6, in <module>
        from ._tree_ensemble import convert_tree_ensemble as _convert_tree_ensemble
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\converters\xgboost\_tree_ensemble.py", line 6, in <module>
        from ...models.tree_ensemble import TreeEnsembleRegressor as _TreeEnsembleRegressor, TreeEnsembleClassifier
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\models\__init__.py", line 6, in <module>
        from . import datatypes
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\models\datatypes.py", line 12, in <module>
        from ..proto import FeatureTypes_pb2 as _FeatureTypes_pb2
      File "C:\Users\reyno\AppData\Local\Temp\pip-req-build-c80vbasj\coremltools\proto\FeatureTypes_pb2.py", line 6, in <module>
        from google.protobuf import descriptor as _descriptor
    ModuleNotFoundError: No module named 'google'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by vartularora** [comment]
I did the installed the following 3 to make it work. (I installed it on Windows 10, 64 bit)
pip install google
pip install google.cloud.bigquery
pip install google-cloud-translate

**Comment by QuinnRadich** [comment]
Apologies for the delay in this response.

I've been discussing this matter with the ML engineering team, as we work to make larger updates across the docset. This page will be updated soon with a slew of new information, including updated instructions to CoreMLTools installation.

Thank you for your patience, and for the good suggestions in this thread.
